### ISSUE TITLE
ImportError: cannot import name 'plyutils'

### ISSUE THREAD

**Issue by mojoee** [sw-gong/coma#3]
thanks for the great work! I wanted to reimplement it on my machine and run into the following issue

when running the preprocess.py script, I cannot plyutils. Where does this script come from`?

all output code follows...

(venv) tim@tim-System-Product-Name:~/Documents/Moritz/3DReconstruction/CoMA/comatf$ python3 processData.py --data ./data/COMA_data --save_path ./data/processed_data/
Preprocessing Slice Time Data
./data/COMA_data
train data of size:  18415
./data/COMA_data
test data of size:  2050
  0%|                                                                                                                                                                              | 0/18415 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "processData.py", line 25, in <module>
    main()
  File "processData.py", line 19, in main
    generateSlicedTimeDataSet(args.data, save_path)
  File "/home/tim/Documents/Moritz/3DReconstruction/CoMA/comatf/facemesh.py", line 251, in generateSlicedTimeDataSet
    MakeSlicedTimeDataset(folders=[data_path], dataset_name=os.path.join(save_path, 'sliced'))
  File "/home/tim/Documents/Moritz/3DReconstruction/CoMA/comatf/facemesh.py", line 136, in __init__
    self.train_vertices = self.gather_data(self.train_datapaths)
  File "/home/tim/Documents/Moritz/3DReconstruction/CoMA/comatf/facemesh.py", line 168, in gather_data
    face_mesh = Mesh(filename=mesh_file)
  File "/home/tim/Documents/Moritz/3DReconstruction/CoMA/comatf/psbody/mesh/mesh.py", line 67, in __init__
    self.load_from_file(filename)
  File "/home/tim/Documents/Moritz/3DReconstruction/CoMA/comatf/psbody/mesh/mesh.py", line 461, in load_from_file
    serialization.load_from_file(self, filename)
  File "/home/tim/Documents/Moritz/3DReconstruction/CoMA/comatf/psbody/mesh/serialization/serialization.py", line 412, in load_from_file
    self.load_from_ply(filename)
  File "/home/tim/Documents/Moritz/3DReconstruction/CoMA/comatf/psbody/mesh/mesh.py", line 464, in load_from_ply
    serialization.load_from_ply(self, filename)
  File "/home/tim/Documents/Moritz/3DReconstruction/CoMA/comatf/psbody/mesh/serialization/serialization.py", line 431, in load_from_ply
    from psbody.mesh.serialization import plyutils
ImportError: cannot import name 'plyutils'

**Comment by cuixin1992** [comment]
Hi~ Did you solve the problem? I got the same problem ㅠㅠ

**Comment by karan00713** [comment]
@mojoee @cuixin1992  did you solved the problem? i'm too facing this error !

**Comment by Johnren1111** [comment]
I also meet this problem!

**Comment by mojoee** [comment]
sorry, I do not remember how or if I fixed this problem. I think we need to follow the exact installation instructions in the readme
